### ISSUE TITLE
Looking for chars in locations

### ISSUE THREAD

**Issue by DarkTl** [XelaPy/PyTFall#101]
*Do not forget to update before the release good traits for gm.enter_location, especially for new locations.

**Comment by XelaPy** [comment]
Noted.

**Comment by DarkTl** [comment]
There is one more issue. It's not unusual to see 2 or 3 copies of the same random character in one location, often with the same picture. It doesn't look good. We probably will have to limit it.

**Comment by DarkTl** [comment]
Well, actually I also meant that I'll need to update traits and occupations themselves :smile:

**Comment by XelaPy** [comment]
- Don't forget that there are goodoccupations and badoccupations now, instead of occupations. I am closing this.
