### ISSUE TITLE
Review some basic form of Interactions/GM module before Next Release.

### ISSUE THREAD

**Issue by XelaPy** [XelaPy/PyTFall#102]
I think the code for it is in pretty good shape, I'll try to review and update it tomorrow so it's acceptable for the next release and close all related issues.

Mainly it is the sorting that needs to be upgraded to modern tags and traits.

**Comment by DarkTl** [comment]
I have a hard time with new interactions, I wasted all my imagination on improving old ones, thus cannot come up with new ones for now. I'll need more time, or a new writer :smile:

**Comment by XelaPy** [comment]
This was meant to be an issue about the traits and tags. This is now fixed, content can be upgraded through separate issue(s).
