### ISSUE TITLE
Gifts logics and occupations

### ISSUE THREAD

**Issue by DarkTl** [XelaPy/PyTFall#114]
- "occupations" field should be rewritten to work with general occupations instead of our old occupations
- perhaps cblock should be replaced by more complex system that make repeatable gifts uneffective and even bad.

**Comment by XelaPy** [comment]
First one (occs) are already working this way.

What are your thoughts on the second issue?

**Comment by DarkTl** [comment]
Well, instead of blocking, cblock field (or some another field) could control how effective the gift will be. I suppose gifts already have a counter of some kind that shows how many turns left before you can use them again.

So when you give a gift, counter += counter + cblock. If counter was = 0 before it, ie the gift wasn't repeatable, it works as it should. 

If counter was < cblock and <> 0 then dismod = dismod*(cblock-counter)/cblock. Ie if we have cblock 4 and counter 2, then dismod == dismod * 0.5.

If counter >= cblock, it's a bad gift, and disposition = disposition - dismod.

**Comment by DarkTl** [comment]
To clarify, I want to use a system when disposition change = dismod + sum of all traits modifiers. I will rebalance all the numbers of course. Ie with dismod 5 and nerd trait -10 disposition change will be -5.

Though negative values are not compatible with disposition = disposition - dismod from the previous post, so the formula should be improved a bit.

**Comment by XelaPy** [comment]
I think that it may be a better idea to create a new interaction where chars say that they were recently given the gift already and do not want it anymore. It'll be a more straight-forward system. What do you think?

**Comment by DarkTl** [comment]
Alright, let's do it:
- Disposition change =  dismod + sum of all traits modifiers
- If counter < cblock and <> 0 then dismod = dismod*(cblock-counter)/cblock
- If counter >= cblock, she refuses to take it, and we drop disposition a bit.
