### ISSUE TITLE
An option to add temporary locations on the map

### ISSUE THREAD

**Issue by DarkTl** [XelaPy/PyTFall#115]
When during quest you need to visit a certain npc or go to a certain place, and they are only useful for that quest and never will be useful after the quest, unlike our witch for example who is also a shopkeeper, we probably need to add this place (or npc house) to the map somehow. And then remove it.
We have a list of locations, we probably could just add it there and mark somehow to make noticeable.

**Comment by XelaPy** [comment]
This is not very hard to do since most of the code is there already (hide system for locations), I guess we need an overlay menu of some kind to add right to the map, this also needs discussion of GUI and general features.

**Comment by XelaPy** [comment]
We've discussed this and already have one hidden location.
