### ISSUE TITLE
Png pictures and backgrounds

### ISSUE THREAD

**Issue by DarkTl** [XelaPy/PyTFall#138]
We have some backgroundless, non sprite png pictures. Atm they have black background when the game shows them. It doesn't look well, non sprite pics with "no bg" tag should have white background.

**Comment by XelaPy** [comment]
They do not have any background... they are just using whatever it is there when they are shown. Can you name places where you have issues with this so I can take a look if backgrounds there can be replaced when we detect a no bg image?

**Comment by DarkTl** [comment]
Profile pics and pics inside next day reports at very least. GM screen too.

**Comment by XelaPy** [comment]
May not be worth it but it's doable... we can condition background off image having no bg tag. I do however think that for some characters white background be just as bad as black is for others.

**Comment by DarkTl** [comment]
Maybe gray then? :)
I don't like black there, it looks too grim without a reason.

**Comment by XelaPy** [comment]
It'll prolly have to be done with Gimp/PS because I can't recolor inner-frame without messing up boarders as well. It's not a priority anyhow.
