### ISSUE TITLE
Random Character generation functionality.

### ISSUE THREAD

**Issue by XelaPy** [XelaPy/PyTFall#152]
Something that we'll prolly want for the beta but never actually discussed in detail or that I've even prototypes... We need a better system than the randomized 0 lvl rchars addons when locations get empty routine.

**Comment by DarkTl** [comment]
I figured we'll have a field in rchars data files that will provide level range for randint.

**Comment by XelaPy** [comment]
No... this is a core code thing, no JSON this time.

**Comment by XelaPy** [comment]
Done!
