### ISSUE TITLE
Arena: Winning screen and theme

### ISSUE THREAD

**Issue by XelaPy** [XelaPy/PyTFall#158]
There might as well not be a screen for a complete victory... it's a half baked, piece of cr@p without a background...

Better presentation is needed.

**Comment by DarkTl** [comment]
http://www.tintuclol.com/wp-content/uploads/bieu-tuong-chien-thang-moi-lmht.png
http://drewstudio.deviantart.com/art/Game-GUI-Panel-448347004

Also there is Agarest folder in my db. There are dds files, I think I have a victory screen there too.

**Comment by XelaPy** [comment]
I like the top one! Gonna play with it a bit.
