### ISSUE TITLE
Add and Advance Battle Skills (BE)

### ISSUE THREAD

**Issue by XelaPy** [XelaPy/PyTFall#17]
Battle Engine must have better support for weapon skills and maybe a couple of special attacks.

**Comment by DarkTl** [comment]
Possible BE improvements after the next release:
- Elemental weapons and armor/rings/etc. 1/2 of elemental weapon damage is elemental, 1/2 is normal weapon damage. Armor/rings/etc. give small protection vs some element.
- Effects that change stats during battle (increase or decrease).
- Skills for every weapon type, with chance to hit and chance to crit based on them.

**Comment by XelaPy** [comment]
These ideas are not related to the issue. I just wanted to generalize code in such a way that weapon attacks would allow for the same flexibility as magic skills, which I have.
