### ISSUE TITLE
Fighters skills

### ISSUE THREAD

**Issue by DarkTl** [XelaPy/PyTFall#170]
- Melee fighters are lacking BE skills compared to mages, even though we have plenty of animations for them. I imagine they should support critical hits and calculate damage based on attack and defense like normal attacks, and use vitality and sometimes health to be activated. 
Really, we cannot make a release when all non-mage fighters have just one basic skill.

- Since we have different weapons, these skills should be tied to base attack types. Like, some ranged skill could require BowAttack or ThrowAttack available to be used.

- We have base attack type in characters jsons that should be used if they are unarmed. Equipping a weapon though should add a basic skill provided by that weapon (like swordattack for a sword) to attacks list, meaning we should carefully handle cases when a character already has swordattack, just like with traits.

- Support for absolute values for cost of spells and battle skills, like 50% of max mp, would help to balance powerful high level skills without making them impossibly demanding. This should work in addition to normal cost, to prevent low level mages from using it. Like, cost = 100 abs_cost=50 mean it costs 50% of mp, and these 50% should be at least 100.

**Comment by XelaPy** [comment]
I like some of this... there shouldn't be much in code that prevents multiple normal attacks...

**Comment by DarkTl** [comment]
Absolute cost and health/vitality cost are done.
