### ISSUE TITLE
Events/Quests Start/End cases.

### ISSUE THREAD

**Issue by XelaPy** [XelaPy/PyTFall#171]
- Go over all events and quests to make sure that they are executed and ended appropriately. (keeping contexts in check)

**Comment by DarkTl** [comment]
It's probably the same as #125.

**Comment by XelaPy** [comment]
Yeah, I should have added a comment to that one. It's very important to make sure we don't jump away from default event setups to end them because that will create really, really weird bugs.

**Comment by XelaPy** [comment]
Duplicate...
