### ISSUE TITLE
A function to remove character from GMs 

### ISSUE THREAD

**Issue by DarkTl** [XelaPy/PyTFall#178]
After certain actions we want character to be removed from GMs immediately, and don't return until N days will pass. Only for non hired obviously, since hired ones always can be found in chars menu.

**Comment by XelaPy** [comment]
`gm.remove_girl(char)`

"Not return until x days passed" we are not going to do before the review but chances of speedy return should be slim in either case, especially if disposition of that char was dropped and we have other chars in the city (and we will as I review spawning/control code).
