### ISSUE TITLE
Add more Special Magical Skills (BE)

### ISSUE THREAD

**Issue by XelaPy** [XelaPy/PyTFall#18]
- Haste
- Confuse
- Sleep
- Death
- Block
- Defend
- etc. etc.. etc...

by Dark:
- Damage over time with randint damage values for all elements. Like, burn for fire spells.
- Buffs and debuffs to battle stats. Attack, defense, agility, magic, crit chance.

**Comment by DarkTl** [comment]
- Damage over time with randint damage values for all elements. Like, burn for fire spells.
- Buffs and debuffs to battle stats. Attack, defense, agility, magic, crit chance.
