### ISSUE TITLE
Update for Beta:

### ISSUE THREAD

**Issue by XelaPy** [XelaPy/PyTFall#184]
- Realtor
- Recheck all events
- Review Taxes

**Comment by XelaPy** [comment]
- Wrap up Graveyard Location:

There should be at least basic unique functionality like look at the list of dead characters, even if we don't use them somehow (yet).

**Comment by XelaPy** [comment]
- Figure out best logic for items buying/equipping.
Autobuy/equip methods. They do work reasonably well as it is, might require a go over just in case, both content and code.

**Comment by XelaPy** [comment]
- Remove empty filters from item screen.
Shouldn't be hard and this makes a heck load of sense...

**Comment by XelaPy** [comment]
- Tavern Events
There are quite many lines for generic events inside the tavern, including brawls (which could easily be done in BE). But the code wasn't completed and also interrupted quests, so I disabled it for now.

Still, we should figure out how to prevent it from bothering quests and finish it.

**Comment by DarkTl** [comment]
- Perhaps traits bonuses should be visible in gui somehow, atm only descriptions are.
- We could use an option for traits to influence wages. Like "wage": 0.9 would mean total wage * 0.9

**Comment by DarkTl** [comment]
I figured out tavern events made by Cherry and updated them to work with my own design.

**Comment by XelaPy** [comment]
It would seem that all of the above is taken care of!
