### ISSUE TITLE
Matrix improvements

### ISSUE THREAD

**Issue by DarkTl** [XelaPy/PyTFall#185]
- (maybe after beta if it's hard) Coordinates should not be dependent on window size when you write them down. Right now if the window size is not default, it will show you wrong coordinates for matrix which won't work as intended.
- (before beta) An ability to freely add and remove available matrix areas (while outside of the matrix) depending on conditions, like flags. So if you don't need a certain area anymore you can hide it, and vice versa.
- (optional, maybe after beta) an ability to add one or more areas with a preset size and form, but random coordinates. Will be useful for random stuff like finding items.

**Comment by XelaPy** [comment]
All done... needs testing.
