### ISSUE TITLE
more clear expansion packs instructions

### ISSUE THREAD

**Issue by picobyte** [XelaPy/PyTFall#189]
If you clone just the alpha version, the game crashes right at the start. It is a development version, so bugs can be expected, but this early may just scare almost anyone away. You may want to give at least some good contributors a chance to see the potential this game has.

To resolve this:
1) I'll add a few patches to get some of the worst away. 
2) Make the instructions a bit more clear here:
http://www.pinkpetal.org/index.php?topic=3401.0

3) preferable at least add one character and one random character to the repo.

Concerning 2: add some instructions on top, with highlighting:

Place the unique character packages as well as the associated .json file in the 'game/content/chars/' subdirectory of PyTFall. The random girls and the associated .json file are to be placed in the in the 'game/content/**r**chars/' directory. At least one unique char and one random rchar, with their associated .json files, are required to run the game!

Also add some spaces and highlight the random characters sections, to clarify the distinction.

**Comment by DarkTl** [comment]
I added the said instructions to my forum post with packs.

**Comment by picobyte** [comment]
looks good
