### ISSUE TITLE
Poison effect bug in BE

### ISSUE THREAD

**Issue by DarkTl** [XelaPy/PyTFall#229]
Poison works twice: in the beginning of character turn, and then after s/he casts a spell (but silently, without sound effect and animation). Should be only in the beginning

**Comment by XelaPy** [comment]
See if we can add Escape from BE while at it. People keep complaining about endless and pointless fights that last for a long time while everyone does about 5 damage per turn to opponents who have hundreds.

**Comment by XelaPy** [comment]
Update Bestiary, just generate Mobs at level suggested by their files and put core stats on display.
