### ISSUE TITLE
Items GUI

### ISSUE THREAD

**Issue by XelaPy** [XelaPy/PyTFall#27]
Figure out what stat/skill/traits and etc we want shown in items description (if any at all) and code that in.

**Comment by DarkTl** [comment]
You regularly change opinion about showing or not showing skills in gui... Let's stick to one point of view already :)

**Comment by Xela00** [comment]
Yeah, we need to make a decision on this...

**Comment by DarkTl** [comment]
For a start, remove libido from anywhere. I still see it at MC screen at very least.

**Comment by DarkTl** [comment]
I think skills in gui should look like descriptive adjectives. Or maybe stars, like area diffuculty in Gismo's EE concept. Without any numbers, just approximate level.

**Comment by XelaPy** [comment]
I've removed libido from the MCs profile screen. I think we'll leave items info as it is now, at least until we know how to handle skills info better.
