### ISSUE TITLE
gci_kwargs bug

### ISSUE THREAD

**Issue by DarkTl** [XelaPy/PyTFall#277]
Judging by characters items, gci_kwargs["purpose"] = "Slave" works incorrectly and gives to slaves anything but slaves items. With some luck, you can buy a slave for less money than her equipment costs.

**Comment by DarkTl** [comment]
Not fixed. Now they bhave slaves items **in addition** to others, not instead of others.

**Comment by XelaPy** [comment]
Closing this down for now...
