### ISSUE TITLE
Traits Balance

### ISSUE THREAD

**Issue by XelaPy** [XelaPy/PyTFall#310]
We have traits that basically ruin the game and make tons of chars useless sh!te. There is creating weaknesses, which is great... there is breaking design.

Reported so far, which we didn't fix yet:
- Slim
- Lolita
- Alien

But traits should be checked for the imbalance in general.

**Comment by DarkTl** [comment]
I figured it's because characters level 10 times per day due to exp imbalance.

**Comment by DarkTl** [comment]
Ok, then many traits have negative stats mod upon level up. These traits affect constitution, thus AP, so players noticed it. But Manly affects agility in the same way.

**Comment by XelaPy** [comment]
Part of the issue is when it's applied to core traits. Too many chars are affected. And it can be x per y levels. Doesn't need to be on every level-up. Traits should no ravage characters like this.
