### ISSUE TITLE
stuck in Home, Work or Action

### ISSUE THREAD

**Issue by picobyte** [XelaPy/PyTFall#333]
When you have a girl and you press Home, Work or Action (either form her character screen or the multi character screen), you can get kind of stuck, nothing works anymore until you press Escape. I encounter this early game, so possibly there are no options available.
Pytfall v0.7 linux OS. Good job BTW.

**Comment by DarkTl** [comment]
You are supposed to pick one of the options from the menu that shows when you click on Home, Work or Action before you can continue.

**Comment by Marrowgarr** [comment]
Having the same issue on Windows 10. Can confirm the options menu is not showing. Using Pytfall v0.7

**Comment by XelaPy** [comment]
Awesome, I am closing this one for now. We just did tons of testing under different conditions, seems to be working for us.
