### ISSUE TITLE
Shopping together option

### ISSUE THREAD

**Issue by DarkTl** [XelaPy/PyTFall#38]
Which worked for some time like two years ago, but not anymore :)
I currently removed it from gui, but would be cool to rewrite and restore it.

Original algorithm was based on occupations, when characters welcomed items helping them at work. That's... not really the best concept, 'cause that's not why most people visit any shops most of the time.
I think the system should look like:
- either you select a shop, or the character does it, I'm not sure what is the best option here.
- There she chooses something based on autobuying system and you can buy it, providing that you have enough money.
- Or you choose an item by yourself if solution based on autobuying system is too difficult. And then we run checks with item's price and type and maybe something else like her inventory (does she has such an item already or not).

**Comment by XelaPy** [comment]
Consolidated
