### ISSUE TITLE
Add new "general sex skill" to schools and maybe jobs.

### ISSUE THREAD

**Issue by XelaPy** [XelaPy/PyTFall#4]
- Dark added new skill but I do not believe it is active outside of Interactions atm while it should be.

**Comment by DarkTl** [comment]
Schools will have it soon. Jobs should be rewritten a lot anyway.

**Comment by DarkTl** [comment]
Schools have it. I'll add it to some items a bit later.

**Comment by DarkTl** [comment]
Items have it.

**Comment by Xela00** [comment]
And you're still not linking this issues url to relevant pushes :)

**Comment by DarkTl** [comment]
How is this useful to anyone?

**Comment by Xela00** [comment]
Look at our commit history, it has #1,2,3,4,5 and etc. attached to it. Also GitHub automatically writes to the Issue that there was an update.

It is very useful for very obvious reasons.
