### ISSUE TITLE
Fix Tags in Jobs

### ISSUE THREAD

**Issue by XelaPy** [XelaPy/PyTFall#44]
- Whore Job, main tags fixed but many of bad tags are not yet excluded.
- It may be a good idea to split the job in 4 logical parts.
- - Add proper skills to lesbian fork.
- - Check if the rest of the tags/skills are sound for rest of the jobs.

This is in addition to main jobs restructuring in the #1.

**Comment by DarkTl** [comment]
I rewrote rest and whore jobs. In order to do it for other jobs I need them to be available and stable, without CTDs.

**Comment by XelaPy** [comment]
This now works? I think...
