### ISSUE TITLE
SE and its new GUI

### ISSUE THREAD

**Issue by DarkTl** [XelaPy/PyTFall#50]
Ok, so we have much better gui without logic behind it. 
Gismo's ideas: http://www.pinkpetal.org/index.php?topic=1291.msg34766#msg34766
I agree with everything there. We need a system, probably based on json, to create locations for SE.
- Name of area and its locations, mobs and their levels, items that you can find there, and how many days each area may take.
- An ability to set labels inside locations during explorations and thus make random events. Like 40% chance to call label chest_gold if you have a character with assassin class trait which gives you randint(50, 100) gold, as a very simple example of event.
- Simulated battle engine for SE. I'm not sure how good our current one, I bet it's too simple :smile:

**Comment by Xela00** [comment]
Yeap, SimPy is going to work really well here I expect. I have a bunch of ideas on how to get things done, just need to wrap up the jobs first.
