### ISSUE TITLE
Add complex tags lookup method.

### ISSUE THREAD

**Issue by XelaPy** [XelaPy/PyTFall#53]
Referenced in threads:

http://www.pinkpetal.org/index.php?topic=1291.msg35786#msg35786
http://www.pinkpetal.org/index.php?topic=1291.msg35784#msg35784

**Comment by Xela00** [comment]
http://www.pinkpetal.org/index.php?topic=1291.msg35794#msg35794

**Comment by XelaPy** [comment]
Done for the interactions at least. I may code in a general one at some point but only if required.
