### ISSUE TITLE
City map, its locations and characters

### ISSUE THREAD

**Issue by DarkTl** [XelaPy/PyTFall#56]
Time to make stuff clear.
- We don't need 3 different maps, it's a lot of work with no real reason. Gismo's map's enough. I will use others in scenes.
It also means to make sure that we blow up the correct city in the intro, ie dark one.

- Locations should be unlocked via arbitrary means. Like quests for example.

- You should be able to find characters with friend status (if they are not hired, because you can find hired ones anytime already) anytime by going to thier home. It means a location with a girl room background (have plenty of them) where we run usual GM label. I suppose it means to have a friend list at MC's screen somewhere, where all friends are listed.
It will help greatly with quests, when you just go to them instead of wandering around the city for many turns looking for someone you already know well enough.

- There should be options to tie characters to a cetain location via arbitrary means. Example: all chars with naruto origin can be found in their village only until you hire them. Example №2: all chars with "pure elf" race string should be in some elven city that we'll have in the future.

- While we here, might as well add to the map locations that I know I'll need for the next release: graveyard and hidden village. Maybe Gismo can do it if he's not busy.

**Comment by XelaPy** [comment]
*Please start separate Issues, it's much easier to work with requests when they are split in small parts.*

- I have disabled all maps except Gismos
- Maps are now loaded from JSON, JSON file allows a new "hidden"=true/"hidden"=false clause for each separate location.
- Gismo is very busy atm. It is perfectly possible to place these locations as as buttons using the icons in the meanwhile.
