### ISSUE TITLE
Standardise a way to put all characters from the same origin at one location

### ISSUE THREAD

**Issue by XelaPy** [XelaPy/PyTFall#59]
- Test if just changing location from "city" and/or "slavemarket" to something unique would do the trick.

**Comment by DarkTl** [comment]
To clarify: sometimes we want character in some specific location only, but sometimes we want to hide a character completely until some quest will be completed. 
So there should be a way to change location ingame, for example at the beginning it will be "none" ie you cannot find that character no matter what, and then we change it to "village" meaning you can find the character there from now on.
