### ISSUE TITLE
Matrix improvements

### ISSUE THREAD

**Issue by DarkTl** [XelaPy/PyTFall#74]
- somehow we need to enter/exit matrix mode during scene. While there are other ways, ideally there should be a button for that. The problem is that we don't know for sure if button's position will be acceptable for any picture, in some cases it might overlap some important element.
So ideally its coordinates should be changable when needed.

Another option is to put it in some corner and make small to make sure it won't overlap something in most cases. But it will look less pretty.

- In some cases we could use tooltips to show the name of the object, while in others we shouldn't show anything like that. I suppose if the object has an optional "name" field in json, then we will show it as a tooltip, and vice versa.

However, it might be problematic to show tooltip without overlaping a major part of picture by its field. If we'll add such a function, it should use much less field that the one we use for dialogues in scenes.

**Comment by XelaPy** [comment]
First part of this is done...

Tooltip, how about we show tooltips from left/right/top/bottom of whatever is focused on the screen, position will be determined by the location of the object on screen? We'll have this properties:

- "tooltip": "some string"
Tooltip will be shown if this is provided.
- "tooltip_align": (0.5, 0.5)
This will override the default setting I described above and align the tooltip accordingly.

**Comment by DarkTl** [comment]
Alright, let's do it.

**Comment by XelaPy** [comment]
Automatic placement turned out in weird code so I've added:

"place": "left"

instead.

"right", "top", "bottom" are the other options. "align" overrides all of this. Default is "left" (taken if only "tooltip" is provided).
