### ISSUE TITLE
Look around option in locations

### ISSUE THREAD

**Issue by DarkTl** [XelaPy/PyTFall#78]
Which is currently based on one single button and probably one dice could be improved using our matrix, when you have to look for available spots, not just press one button. We could make spots to appear randomly to make searching interesting.

**Comment by XelaPy** [comment]
Entering locations and look around button both trigger events. Events can show screens like our polymatrix thus enabling the functionality like you've described so I don't think that this is something we need to code in.

There are examples of similar things in Nami/From events but it's prolly not east to put the two together.

**Comment by DarkTl** [comment]
I mostly mean those events when you found random amount of money or a random item after looking around. If we'll use matrix somehow to make items searching more complex and interesting, that would be nice.

**Comment by XelaPy** [comment]
We can do both... it's actually fairly easy to get done without writing new code but I don't have time to make matrix atm. Whenever I am not fixing something up so you/Gismo can add new content/graphics, I am coding jobs. I'll put in a few more hours into that tomorrow evening, it's going really well :)

**Comment by XelaPy** [comment]
We're done with this? This is basically the very same thing as starting a normal event and adding a polymatrix screen to it.
