### ISSUE TITLE
Fix unique character support

### ISSUE THREAD

**Issue by XelaPy** [XelaPy/PyTFall#81]
We use many characters that are not supported by most normal fonts.

**Comment by DarkTl** [comment]
Can renpy use multiple fonts in the same line? That might be a good solution if it can.

**Comment by XelaPy** [comment]
I am planning to make a list of all of the unique characters we use and analyze strings for them whereever appropriate, for those characters, default font will be used. It should serve as a solution.

**Comment by DarkTl** [comment]
Ideally, it should be something like a json that contains all unusual characters that require a universal font, This way anyone can freely add new ones when needed.

**Comment by XelaPy** [comment]
Yeah, I think that I know how to do this now... gonna try fixing it next.

**Comment by XelaPy** [comment]
I consider this fixed, we just need to track down all places where this might occur and make sure that fixed fonts are used there.
