### ISSUE TITLE
Figure out a good way to store interrim jobs data.

### ISSUE THREAD

**Issue by XelaPy** [XelaPy/PyTFall#97]
Prolly best done through flags.

**Comment by DarkTl** [comment]
interrim?..

**Comment by XelaPy** [comment]
This is for inside jobs, in the past, each job was a unique instance so it was an easy choice, not jobs are more like groups of funcs to log data while SimPy is handling the logic.

I've been going backwards and forwards with this choices for weeks. Now I've finally decided to use flags of characters and teams (means adding frags to teams as well).

These flags will start with "jobs" and be destroyed at the end of next day (which means no normal flag may start with jobs).
